config:
  project_repos:
    FAIR_eva:
      branch: master
      repo: https://github.com/EOSC-synergy/FAIR_eva

sqa_criteria:
  QC.Sty:
     repos:
       dataverse:
         container: dataverse
         commands:
          - sh /secrets/db_sample.sh
  QC.FAIR:
    repos:
      fair_assessment:
        container: fair
        commands:
        - curl http://fairserver:9090/v1.0/rda/rda_all
        - sh /fair_assessment/test/test_upload.sh
        - curl "http://dataverse:8080/api/datasets/export?exporter=dataverse_json&persistentId=doi:10.34622/datarepositorium/SGXCQO"
        - curl "http://0.0.0.0:8080/api/datasets/export?exporter=dcterms&persistentId=doi:10.34622/datarepositorium/SGXCQO"
        - curl "http://0.0.0.0:8080/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=doi:10.34622/datarepositorium/SGXCQO"
        - >-
          curl --location --request POST "http://fairserver:9090/v1.0/rda/rda_all"
          --header "Content-Type: application/json" 
          --header "Cookie: Cookie_1=foobar"
          --data-raw "{ \"id\": \"https://doi.org/10.34622/datarepositorium/SGXCQO\", \"repo\": \"oai-pmh\", \"oai_base\": \"http://dataverse:8080/oai\", \"lang\": \"en\" }"

environment:
  JPL_WORKSPACEDEBUG: "true"
  JPL_WORKSPACEDEBUGTIMEOUT: 1200

timeout: 3600
